---
- name: Instalar PyPy en nodos Flatcar
  hosts: all
  become: true
  gather_facts: false
  vars:
    pypy_version: pypy3.9-v7.3.9-linux64
  tasks:
    - name: Descargar archivo de PyPy
      ansible.builtin.raw: |
        wget -q -P /opt/ https://downloads.python.org/pypy/{{ pypy_version }}.tar.bz2
    - name: Extraer archivo de PyPy
      ansible.builtin.raw: |
        tar -xf /opt/{{ pypy_version }}.tar.bz2 -C /opt
    - name: Eliminar archivo comprimido de PyPy
      ansible.builtin.raw: |
        rm -rf /opt/{{ pypy_version }}.tar.bz2
    - name: Crear directorio /opt/bin
      ansible.builtin.raw: |
        mkdir -p /opt/bin
    - name: Crear enlace simbólico para python
      ansible.builtin.raw: |
        ln -s /opt/{{ pypy_version }}/bin/python3 /opt/bin/python
