---
- name: Actualizar configuración de K3s para usar la IP VIP
  hosts: k8s_cluster
  become: true
  gather_facts: true

  vars:
    vip_ip: "10.17.5.10"
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    k3s_service_path: "/etc/systemd/system/k3s.service"
    tls_san_option: "--tls-san {{ vip_ip }}"

  tasks:
    - name: Modificar el endpoint del kubeconfig para apuntar a la VIP
      replace:
        path: "{{ kubeconfig_path }}"
        regexp: 'server: https://.*:6443'
        replace: 'server: https://{{ vip_ip }}:6443'
      when: "'masters' in group_names or 'workers' in group_names or 'storage' in group_names"

    - name: Agregar --tls-san para la VIP en el servicio de K3s
      lineinfile:
        path: "{{ k3s_service_path }}"
        backrefs: yes
        regexp: '^(ExecStart=.*)$'
        line: '\1 {{ tls_san_option }}'
      when: "'masters' in group_names"

    - name: Eliminar certificados TLS para regenerarlos con la nueva VIP
      file:
        path: "/var/lib/rancher/k3s/server/tls"
        state: absent
      when: "'masters' in group_names"

    - name: Recargar configuración de systemd y reiniciar K3s
      systemd:
        daemon_reload: true
        name: k3s
        state: restarted
      when: "'masters' in group_names"

    - name: Verificar que el kubeconfig apunta a la VIP
      command: grep 'server: https://{{ vip_ip }}:6443' {{ kubeconfig_path }}
      register: kubeconfig_check
      changed_when: false
      failed_when: kubeconfig_check.rc != 0

    - name: Mostrar resultado de la verificación
      debug:
        msg: "El kubeconfig ha sido actualizado correctamente para usar la VIP."
      when: kubeconfig_check.rc == 0