---
- name: Reemplazar endpoint API por IP VIP y reiniciar K3s
  hosts: masters
  gather_facts: false
  vars:
    vip_ip: "10.17.5.10"
  tasks:
    - name: Agregar --tls-san VIP al ExecStart en k3s.service si no existe
      raw: >
        grep -q -- '--tls-san {{ vip_ip }}' /etc/systemd/system/k3s.service || \
        sed -i '/ExecStart=/ s|\\(--tls-san [^ ]*\\)|\\1 --tls-san {{ vip_ip }}|' /etc/systemd/system/k3s.service

    - name: Reemplazar IP en k3s.yaml por la VIP
      raw: >
        sed -i 's|server: https://.*:6443|server: https://{{ vip_ip }}:6443|' /etc/rancher/k3s/k3s.yaml

    - name: Reiniciar K3s correctamente
      raw: |
        systemctl daemon-reexec
        systemctl daemon-reload
        systemctl restart k3s

    - name: Verificar API con curl (401 esperado)
      raw: |
        curl -k https://{{ vip_ip }}:6443 || true

- name: Reemplazar endpoint del server en workers
  hosts: workers
  gather_facts: false
  vars:
    vip_ip: "10.17.5.10"
  tasks:
    - name: Reemplazar --server en k3s-agent.service por IP VIP
      raw: >
        sed -i 's|--server https://.*:6443|--server https://{{ vip_ip }}:6443|' /etc/systemd/system/k3s-agent.service

    - name: Reiniciar K3s Agent correctamente
      raw: |
        systemctl daemon-reexec
        systemctl daemon-reload
        systemctl restart k3s-agent

    - name: Esperar unos segundos para estabilizar
      raw: sleep 5