---
- name: Reemplazar endpoint API por IP VIP y reiniciar K3s
  hosts: k8s_cluster
  gather_facts: false
  become: true

  tasks:

    - name: Verificar si existe el archivo k3s.yaml
      ansible.builtin.raw: |
        if [ -f /etc/rancher/k3s/k3s.yaml ]; then
          echo "exists"
        else
          echo "missing"
        fi
      register: k3s_yaml_status
      changed_when: false

    - name: Copia de seguridad de k3s.yaml si existe
      ansible.builtin.raw: |
        cp /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s.yaml.bak
      when: "'exists' in k3s_yaml_status.stdout"

    - name: Reemplazar IP del API server en k3s.yaml
      ansible.builtin.raw: |
        sed -i 's|server: .*|server: https://10.17.5.10:6443|' /etc/rancher/k3s/k3s.yaml
      when: "'exists' in k3s_yaml_status.stdout"

    - name: Regenerar todos los certificados en nodos master
      ansible.builtin.raw: |
        /opt/bin/k3s certificate rotate --force
      when: inventory_hostname in groups['masters']

    - name: Reiniciar servicio k3s o k3s-agent
      ansible.builtin.raw: |
        if systemctl list-units --full -all | grep -q 'k3s-agent.service'; then
          systemctl restart k3s-agent
        else
          systemctl restart k3s
        fi

    - name: Validar conexión al API Server por la IP VIP (solo masters)
      ansible.builtin.raw: |
        curl -sk https://10.17.5.10:6443/version || exit 1
      when: inventory_hostname in groups['masters']