---
- name: Reemplazar endpoint API por IP VIP y reiniciar K3s
  hosts: k8s_cluster
  gather_facts: false
  become: true

  tasks:

    - name: Verificar si existe el archivo k3s.yaml
      ansible.builtin.command: test -f /etc/rancher/k3s/k3s.yaml
      register: k3s_yaml_status
      ignore_errors: true

    - name: Copia de seguridad de k3s.yaml si existe
      ansible.builtin.command: cp /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s.yaml.bak
      when: k3s_yaml_status.rc == 0

    - name: Reemplazar IP del API server en k3s.yaml
      ansible.builtin.command: >
        sed -i 's|server: .*|server: https://10.17.5.10:6443|' /etc/rancher/k3s/k3s.yaml
      when: k3s_yaml_status.rc == 0

    - name: Regenerar certificados en masters
      ansible.builtin.command: /opt/bin/k3s certificate rotate --force
      when: inventory_hostname in groups['masters']

    - name: Reiniciar servicio k3s o k3s-agent
      ansible.builtin.shell: |
        if systemctl list-units --full -all | grep -q 'k3s-agent.service'; then
          systemctl restart k3s-agent
        else
          systemctl restart k3s
        fi
      args:
        executable: /bin/sh

    - name: Validar conexión al API Server por VIP (solo masters)
      ansible.builtin.command: curl -sk https://10.17.5.10:6443/version
      when: inventory_hostname in groups['masters']